version: '3'

services:
  frontend:
    command: npm run dev
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/usr/src/app/

  api:
    command: npm run dev
    volumes:
      - ./api/src:/usr/src/app/src
